# Generated by Django 5.2.4 on 2025-07-17 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_confession_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='content',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='confession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
