# Generated by Django 5.2.4 on 2025-07-17 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_confession_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.confession')),
            ],
        ),
    ]
