# Generated by Django 5.2.4 on 2025-07-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_confession_upvotes_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
