# Generated by Django 5.2.4 on 2025-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
