# Generated by Django 5.2.4 on 2025-07-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_confession_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
