# Generated by Django 5.2.4 on 2025-08-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_confession_created_at_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='mood',
            field=models.CharField(blank=True, choices=[('😊', 'Happy'), ('😢', 'Sad'), ('😰', 'Anxious'), ('😤', 'Frustrated'), ('🤔', 'Confused'), ('❤️', 'Loved')], max_length=10, null=True),
        ),
    ]
